version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - REACT_APP_BACK_LINK=http://host.docker.internal:3000
    restart: unless-stopped